# -*- coding: utf-8 -*-
"""ASSIGNMENT 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JHMY0jg5lUVGSmO5g47fLrUUV2sVHtlf
"""

# Task: Check if a Number is Even or Odd

num = int(input("Enter an integer: "))


if num % 2 == 0:
    result = "even"
else:
    result = "odd"

print(f"The number {num} is {result}.")

# Task 2: Sum of Integers from 1 to 50 Using a Loop

total = 0

for num in range(1, 51):
    total += num

print(f"The sum of integers from 1 to 50 is: {total}")



